project_id = "qasomfndnjuixgjmjwcm"

[functions.create-admin-user]
verify_jwt = false

[functions.change-user-password]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.notify-service-order-email]
verify_jwt = false

[functions.notify-accident-email]
verify_jwt = false

[functions.send-supplier-order-email]
verify_jwt = false

[functions.paypal-charge]
verify_jwt = false

[functions.backup-data]
verify_jwt = false